FROM php:8.2-fpm

RUN apt-get update && apt-get install -y \
    git unzip libzip-dev libonig-dev curl \
    && docker-php-ext-install pdo pdo_mysql zip mbstring pcntl

WORKDIR /var/www/html

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer
COPY . .

RUN composer install --no-dev --optimize-autoloader \
    && php artisan config:clear

CMD ["php", "artisan", "horizon"]
